# Generated by Django 4.2.1 on 2023-07-09 04:34

from django.db import migrations, models
import django.db.models.deletion
import maps.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('name', models.CharField(blank=True, help_text='AEON MALL', max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, help_text='〒000-0000 東京都渋谷区渋谷1-1-1', max_length=255, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order_num'],
            },
        ),
        migrations.CreateModel(
            name='MapImage',
            fields=[
                ('id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=maps.models.upload_to)),
                ('map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maps.map')),
            ],
            options={
                'ordering': ['order_num'],
            },
        ),
        migrations.CreateModel(
            name='MapCategory',
            fields=[
                ('id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('icon_color', models.CharField(blank=True, max_length=255, null=True)),
                ('icon_name', models.CharField(blank=True, max_length=255, null=True)),
                ('icon_size', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_categories', to='projects.project')),
            ],
            options={
                'ordering': ['order_num'],
            },
        ),
        migrations.AddField(
            model_name='map',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='maps.mapcategory'),
        ),
        migrations.AddField(
            model_name='map',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='projects.project'),
        ),
    ]
