# Generated by Django 4.2.1 on 2023-06-12 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_status'),
        ('maps', '0006_alter_mapcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapcategory',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_categories', to='projects.project'),
        ),
    ]
