# Generated by Django 4.2.1 on 2023-06-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_map_description_map_icon_name_map_icon_size_map_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapcategory',
            name='icon_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
