# Generated by Django 4.2.1 on 2023-07-09 04:34

from django.db import migrations, models
import django.db.models.deletion
import galleries.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('file', models.FileField(upload_to=galleries.models.upload_to)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=galleries.models.upload_to)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('size', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Galleries',
                'ordering': ['order_num'],
            },
        ),
    ]
