# Generated by Django 4.2.1 on 2023-06-11 11:26

from django.db import migrations, models
import galleries.models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_rename_url_gallery_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=galleries.models.upload_to),
        ),
    ]
