# Generated by Django 4.2.1 on 2023-06-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.projectgroup'),
        ),
    ]
