# Generated by Django 4.2.1 on 2023-06-02 13:45

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.upload_to),
        ),
    ]
