# Generated by Django 4.2.1 on 2023-07-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomplan',
            name='status',
        ),
    ]
