# Generated by Django 4.2.1 on 2023-06-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_plan_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='room_type',
            field=models.CharField(blank=True, help_text='4LDK+WIC+SIC', max_length=255, null=True),
        ),
    ]
