# Generated by Django 4.2.1 on 2023-06-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_plan_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='room_type',
            field=models.CharField(blank=True, help_text='2LDK, 4LDK+WIC', max_length=255, null=True),
        ),
    ]
