# Generated by Django 4.2.1 on 2023-06-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_plan_room_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='kind',
            new_name='plan_type',
        ),
    ]
