# Generated by Django 4.2.1 on 2023-06-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_rename_room_type_plan_madori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan',
            field=models.CharField(blank=True, choices=[('general_plan', '一般図'), ('room_plan', '間取り図')], default='general_plan', help_text='一般図 間取り図', max_length=255),
        ),
    ]
