# Generated by Django 4.2.1 on 2023-06-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_alter_plan_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='measurement',
            field=models.CharField(blank=True, help_text='62.10m²', max_length=255, null=True),
        ),
    ]
