# Generated by Django 4.2.1 on 2023-06-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_alter_plan_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(blank=True, help_text='A, B, 立面図', max_length=255, null=True),
        ),
    ]
