# Generated by Django 4.2.1 on 2023-06-11 11:37

from django.db import migrations, models
import plans.models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_alter_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=plans.models.upload_to),
        ),
        migrations.AlterField(
            model_name='plan',
            name='image',
            field=models.ImageField(upload_to=plans.models.upload_to),
        ),
    ]
