# Generated by Django 4.2.1 on 2023-06-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_generalplan_roomplan_delete_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomplan',
            name='floor',
            field=models.CharField(blank=True, help_text='1F, 2F', max_length=255, null=True),
        ),
    ]
