# Generated by Django 4.2.1 on 2023-06-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0013_roomplan_ppm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomplan',
            name='ppm',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
