# Generated by Django 4.2.1 on 2023-06-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0014_alter_roomplan_ppm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomplan',
            name='ppm',
            field=models.FloatField(blank=True, help_text='1/100', null=True),
        ),
    ]
