# Generated by Django 4.2.1 on 2023-06-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0015_alter_roomplan_ppm'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomplan',
            name='status',
            field=models.CharField(blank=True, choices=[('publish', '公開'), ('archive', 'アーカイブ'), ('list_hidden', '一覧非公開')], default='publish', max_length=255, null=True),
        ),
    ]
