# Generated by Django 4.2.1 on 2023-06-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0016_roomplan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomplan',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomplan',
            name='is_list_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
