branch-defaults:
  development:
    environment: development
    group_suffix: null
global:
  application_name: reactool
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: ap-northeast-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-reactool-2
  repository: null
  sc: git
  workspace_type: Application
