# Generated by Django 4.2.1 on 2023-07-09 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('route_name', models.CharField(blank=True, max_length=255)),
                ('component_name', models.CharField(blank=True, max_length=255)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('front_url_name', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='projects.project')),
            ],
            options={
                'ordering': ['order_num'],
            },
        ),
    ]
