# Generated by Django 4.2.1 on 2023-06-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='url_name',
            new_name='endpoint',
        ),
        migrations.AddField(
            model_name='route',
            name='front_url_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
