# Generated by Django 4.2.1 on 2023-07-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='folder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
