# Generated by Django 4.2.1 on 2023-07-09 04:34

from django.db import migrations, models
import django.db.models.deletion
import panorama.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panorama',
            fields=[
                ('id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, help_text='A, B, (子文字入力してもでアッパーケースに交換)', max_length=100, null=True)),
                ('day_time', models.CharField(blank=True, choices=[('morning', '朝'), ('afternoon', '昼'), ('evening', '夕'), ('night', '夜')], help_text='朝, 昼, 夕, 夜', max_length=100, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=panorama.models.upload_to)),
                ('is_loop', models.BooleanField(default=True, help_text='ループするかどうか')),
                ('is_panoramic', models.BooleanField(default=True, help_text='パノラマ写真かどうか')),
                ('floor', models.IntegerField(default=1, help_text='何階か', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panorama', to='projects.project')),
            ],
        ),
    ]
